# This is a configuration file template for the SCION border router.
# It is instantiated with concrete values in the ControlServer class.
# The structure of this file depends on the SCION version and is thus linked to the binary located in jniLibs.

[general]
id = "border_router"
config_dir = "%s"
reconnect_to_dispatcher = true

[metrics]
prometheus = "127.0.0.1:31445"

[log.console]
level = "%s"
